Pr3.class: Pr3.java
	javac Pr3.java
AssemblerLine.class: AssemblerLine.java
	javac AssemblerLine.java
LiteralPool.class: LiteralPool.java
	javac LiteralPool.java
HashTable.class: HashTable.java
	javac HashTable.java
